import type { Song } from './types'

// Songs are baked into the static build as /songs.json (generated by `make dump-songs`).
export async function fetchSongMap(): Promise<Map<number, Song>> {
  const res = await fetch('/songs.json')
  if (!res.ok) throw new Error('songs.json not found — run: make dump-songs')
  const songs: Song[] = await res.json()
  return new Map(songs.map(s => [s.id, s]))
}
