export interface Song {
  id: number
  name: string
  artist: string
  album: string
  genre: string
  imageUrl: string
  releaseDate: string
  duration: number
}

export interface Playlist {
  id: number
  roleId: string
  agentName: string   // resolved from agentMap
  name: string        // playlist title (generated by agent)
  songIds: number[]
  stake: bigint
  submittedAt: number
  scored: boolean
  score: number
  // enriched after scoring event
  agentPayout?: bigint
  treasuryDelta?: bigint
  treasuryGained?: boolean
}

export interface AgentInfo {
  id: number
  name: string
  roleId: string
}

export type ToastType = 'info' | 'success' | 'warning' | 'error'

export interface Toast {
  id: number
  type: ToastType
  title: string
  body: string
}

export interface ActivityEntry {
  id: number
  ts: number
  event: 'submitted' | 'scored' | 'roundComplete'
  playlistId: number
  roleId: string
  agentName: string
  playlistName?: string
  score?: number
  agentPayout?: bigint
  treasuryDelta?: bigint
  treasuryGained?: boolean
  songIds?: number[]
  stake?: bigint
  // round complete fields
  round?: number
  poolSize?: number
  totalScore?: number
  avgScore10x?: number
}

export interface RoundStat {
  round: number
  avgScore: number   // avgScore10x / 10
}
